# This will configure proxy setting and mount the volumes
- hosts: all_servers_common
  user: ec2-user
  sudo: yes
  vars_files:
    - host_vars/new_nectar.yaml
  vars:
    ansible_ssh_private_key_file: "{{ key1 }}"
  roles:
    - role: openstack-mountvolume
    - role: openstack-common
