# Create volumes snapshot(s)
- name: Create volume snapshot(s)
  os_volume_snapshot:
    state: present
    volume: '{{ item.vol_name }}'
    #'date +%Y-%m-%d-%H-%M-%S' is the timestamp
    display_name: '{{ item.vol_name }}-{{ loopup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}'
    wait: yes
    timeout: 600
    force: yes
    availability_zone: '{{ availability_zone }}'
  loop: '{{ volumes }}'