# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: deadlySins_S3
    vol_size: 50

# Security group
security_groups:
  - name: deadlySins_SG1
    description: "Security group 1"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: deadlySins_SG2
    description: "Security group 2"
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0
  - name: deadlySins_SG3
    description: "Security group 3"
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0  

# Instance
instances:
  - instance_name: deadlySins_S3
    instance_image: 156f4c28-d42d-45a7-8625-616ce5b91392
    instance_key_name: sins101
    instance_flavor: uom.mse.2c9g
