# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: deadlySins_S3
    vol_size: 50

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSh access"
	protocol: tcp
	port_range_min: 22
	port_range_max: 22
    #not a good approach to have ip 0.0.0.0 as everyone can access
	remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
	protocol: tcp
	port_range_min: 80
	port_range_max: 80
    #not a good approach to have ip 0.0.0.0 as everyone can access
	remote_ip_prefix: 0.0.0.0/0

# Instance
instance_name: deadlySins_S3
instance_image: 156f4c28-d42d-45a7-8625-616ce5b91392
#public key
instance_key_name: sins101
instance_flavor: uom.mse.2c9g