# Node will join the couch cluster
- name: Add to {{ansible_eth0.ipv4.address}} cluster 
  command: "docker run -d --name couchdb  --restart always   -p 5984:5984   -p 5986:5986   -p 4369:4369   -p 9100-9200:9100-9200   -e COUCHDB_USER='server_admin'   -e COUCHDB_PASSWORD='password'   -e COUCHDB_SECRET='password'   -e NODENAME='{{ansible_eth0.ipv4.address}}'   couchdb:2.3.0   -setcookie couchdb_cluster"

- command: "chmod +x /mnt/storage/project/CouchDB/create_cluster.sh"

- command: 'sh /mnt/storage/project/CouchDB/create_cluster.sh 5984 5986 "172.26.38.5 {{ansible_eth0.ipv4.address}}"'
