# Download files from GitHub
- name: Create repository for harvester
  file:
     mode: "0777"
     recurse: yes
     path:  "/mnt/storage/project/"
     state: directory

- name: Extracting twitter harvester
  command: git clone https://github.com/knightmatish/CC_assignment_2.git /mnt/storage/project/

# The following line will start the Harvester
- command: 'python3 /mnt/storage/project/Harvester/twitterHandler.py' 
